import puppeteer from "https://deno.land/x/puppeteer@16.2.0/mod.ts";
import { format } from "https://deno.land/std@0.204.0/datetime/mod.ts";

// List of symbols to retrieve prices
const searchsymbols: SymbolConversion[] = [
  { ledger: "EUNL", tradingview: "XETR-EUNL" },
  { ledger: "AUM5", tradingview: "XETR-AUM5" },
  { ledger: "XETR", tradingview: "XETR-XMLD" },
  { ledger: "ETH", tradingview: "ETHEUR" },
  { ledger: "BTC", tradingview: "BTCEUR" },
  { ledger: "DOGE", tradingview: "DOGEEUR" },
  { ledger: "MATIC", tradingview: "MATICEUR" },
  { ledger: "ADA", tradingview: "ADAEUR" },
];

// A ledger journal price item
type PriceLine = {
  comment: string;
  key: string;
  date: string;
  symbol: string;
  price: string;
  currency: string;
};

// Convert ledger journal to tradingview journal
type SymbolConversion = {
  ledger: string;
  tradingview: string;
};

// Tradingview symbols
const tv_symbols: Record<string, PriceLine> = {};

/**
 * Get symbol prices from tradingview website
 * @param symbols - tradingview symbols list
 *
 * @returns tradingview symbol prices
 */
const getTradingviewPrices = async function (
  symbols: SymbolConversion[],
): Promise<PriceLine[]> {
  const url = "https://fr.tradingview.com/symbols";

  // Selector
  const xsel_price =
    `//*[@id="js-category-content"]/div[1]/div[1]/div/div/div/div[3]/div[1]/div/div[1]/span[1]/span`;
  const xsel_currency =
    `//*[@id="js-category-content"]/div[1]/div[1]/div/div/div/div[3]/div[1]/div/div[1]/span[2]/span[1]`;

  const values: PriceLine[] = [];
  console.log(`Try get prices`);

  for (let i = 0; i < symbols.length; i++) {
    const symbol = symbols[i];

    try {
      console.log(`Get ${symbol.tradingview}`);

      // Launch Puppeteer
      const browser = await puppeteer.launch();

      // Create a new page
      const page = await browser.newPage();
      await page.setDefaultTimeout(5000);
      await page.setViewport({ width: 1920, height: 1080 });
      await page.goto(`${url}/${symbol.tradingview}`);

      // get price
      const eprice = await page.waitForXPath(xsel_price);
      const vprice = await page.evaluate(
        // deno-lint-ignore no-explicit-any
        (eprice: any) => eprice.textContent,
        eprice,
      );

      // get currency
      const ecurrency = await page.waitForXPath(xsel_currency);
      const vcurrency = await page.evaluate(
        // deno-lint-ignore no-explicit-any
        (ecurrency: any) => ecurrency.textContent,
        ecurrency,
      );

      const stringdate = format(new Date(), "yyyy-MM-dd");
      const comment = vprice ? "P" : vcurrency ? "P" : "; P";

      const price: PriceLine = {
        comment: comment,
        key: `${stringdate}-${symbol.ledger}-${vcurrency}`,
        date: stringdate,
        symbol: symbol.ledger,
        price: vprice,
        currency: vcurrency,
      };

      values.push(price);

      browser.close();
    } catch (error) {
      console.log(error);
    }
  }

  return values;
};

/**
 * Get symbol informations from ledger journal line
 */
const getSymbolInfoFromLedgerLine = function (line: string): PriceLine {
  const price: PriceLine = {
    comment: "",
    key: "",
    date: "",
    symbol: "",
    price: "",
    currency: "",
  };

  const regex =
    /^([;\sP]{1,2}) ([0-9]{4}-[0-9]{2}-[0-9]{2})\s{2}([A-Z0-9]+) (\d+\.\d+) ([A-Z]+)$/;
  const match = line.match(regex);
  if (regex.test(line) && match) {
    price.comment = match[1];
    price.key = `${match[2]}-${match[3]}-${match[5]}`;
    price.date = match[2];
    price.symbol = match[3];
    price.price = match[4];
    price.currency = match[5];
  }

  return price;
};

/**
 * read ledger prices and convert to Record<string, PriceLine>
 *
 * @param filename - ledger journal filename
 * @param prices - A Record<string, PriceLine> object
 */
const LedgerToPrices = function (
  filename: string,
  prices: Record<string, PriceLine>,
): void {
  if (!filename) {
    console.log("Please define the LEDGER_FILE_PRICES variable");
    Deno.exit(1);
  }

  let journal = "";
  try {
    journal = Deno.readTextFileSync(filename);
  } catch (_) {
    //
  }

  const lines = journal.toString().split("\n");

  lines.forEach((item) => {
    const symbol = getSymbolInfoFromLedgerLine(item);
    if (symbol.key != "") {
      prices[symbol.key] = symbol;
    }
  });
};

/**
 * Add a tradingview symbol prices to Record<string, PriceLine> object
 * @param prices - A Record<string, PriceLine> object
 */
const addTradingviewPricesToPrices = function (
  symbolprices: PriceLine[],
  prices: Record<string, PriceLine>,
): void {
  for (const k in symbolprices) {
    prices[symbolprices[k].key] = symbolprices[k];
  }
};

/**
 * Write Record<string, PriceLine> to ledger journal
 * @param p - Record<string, PriceLine>
 * @param filename - ledger journal filename
 */
const pricesToLedger = function (
  p: Record<string, PriceLine>,
  filename: string,
): void {
  let journal = "; DO NOT EDIT THIS FILE, IT'S GENERATED AUTOMATICALLY\n\n";
  for (const k in p) {
    const line = `${p[k].comment} ${p[k].date}  ${p[k].symbol} ${p[k].price} ${
      p[k].currency
    }\n`;
    journal += line;
  }
  Deno.writeTextFileSync(filename, journal);
};

///////////////////////////////////////////////////////////////////////////////
// main
///////////////////////////////////////////////////////////////////////////////

// Read ledger journal
const LEDGER_FILE_PRICES = Deno.env.get("LEDGER_FILE_PRICES") || "";
LedgerToPrices(LEDGER_FILE_PRICES, tv_symbols);

// Get tradingview prices
const symbolprices = await getTradingviewPrices(searchsymbols);
addTradingviewPricesToPrices(symbolprices, tv_symbols);

// Write ledger journal
pricesToLedger(tv_symbols, LEDGER_FILE_PRICES);
